controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    robot_base_control:
      type: #TBD

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
      # Other controllers
      
/**/robot_base_control:
  ros__parameters:
    type: #TBD
    use_stamped_vel: false
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: #TBD
    right_wheel_names: #TBD
    wheel_separation: 1.90
    wheel_radius: 0.30
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    # Base frame_id
    base_frame_id: base_footprint
    # odom tf will be published by direct laser odometry
    enable_odom_tf: true
    # Publish limited velocity
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
        
        
# TBD: Add here controllers for each moveit group
        
